import pathlib
import json

# Use the 19 golden examples generated by Claude in gemma_core
GOLDEN_DIR = pathlib.Path(__file__).parent / "gemma_core" / "golden_examples"

# Keywords are merged from the original list and gemma_core/corpus_index.json.
# More keywords improve keyword-match accuracy for the 19-scenario fallback.
SCENARIO_KEYWORDS = {
    "product_detail": [
        "商品详情", "详情页", "购买", "划线价",
        "商品", "价格", "商城", "加购", "购物车", "电商",
    ],
    "signup_form": [
        "报名", "表单", "活动报名",
        "姓名", "手机号", "提交", "注册",
    ],
    "product_list": [
        "商品列表", "热销", "新品",
        "货架", "分类", "筛选", "商品网格",
    ],
    "booking_form": [
        "预约", "时段", "日期", "服务预约",
        "预订", "档期", "下单", "reservation",
    ],
    "store_intro": [
        "店铺", "营业时间", "评分", "人均",
        "门店", "地址", "评价",
    ],
    "corporate_homepage": [
        "企业", "官网", "首页", "关于我们", "合作客户",
        "公司", "服务", "landing",
    ],
    "course_detail": [
        "课程", "课时", "主讲", "大纲",
        "老师", "学习", "报名课程", "教学", "lesson",
    ],
    "news_list": [
        "新闻", "资讯列表", "文章列表", "头条",
        "资讯", "feed", "媒体",
    ],
    "news_detail": [
        "新闻详情", "文章详情", "正文", "阅读数", "点赞",
        "评论", "article",
    ],
    "profile": [
        "个人中心", "我的", "会员", "头像", "设置",
        "用户", "VIP",
    ],
    "order_list": [
        "订单", "待付款", "待发货", "查看物流",
        "待收货", "我的订单",
    ],
    "coupon_claim": [
        "领券", "优惠券", "有效期", "满减",
        "领取", "折扣", "优惠", "coupon",
    ],
    "service_pricing": [
        "报价", "套餐", "年付", "月付", "专业版",
        "订阅", "pricing", "价格方案",
    ],
    "job_posting": [
        "招聘", "岗位", "HR", "薪资", "福利",
        "求职", "JD", "职责", "投递", "hiring",
    ],
    "real_estate": [
        "房源", "二手房", "几室几厅", "面积", "地铁",
        "楼盘", "公寓", "学区", "房产",
    ],
    "restaurant_menu": [
        "点餐", "餐厅", "菜品", "加减号",
        "菜单", "美食", "餐饮", "menu",
    ],
    "portfolio": [
        "作品集", "设计师", "案例", "流程",
        "作品", "showcase", "项目展示",
    ],
    "survey": [
        "问卷", "调查", "必填", "提交问卷",
        "题目", "反馈", "调研", "满意度",
    ],
    "contact_us": [
        "联系我们", "留言", "地址", "联系方式",
        "联系", "客服", "电话", "邮箱",
    ],
}

# ─────────────────────────────────────────────────────────────────────────────
# 高质量黄金样例（兜底输出现已改用这 3 个；旧 19 个样例仍完整保留在
# gemma_core/golden_examples 作为「容器/备用」，见 _legacy_get_golden_example_19）。
# ─────────────────────────────────────────────────────────────────────────────
HIGH_QUALITY_DIR = pathlib.Path(__file__).parent / "golden_examples" / "high_quality"

HIGH_QUALITY_KEYWORDS = {
    "product_detail": [
        "商品", "详情", "商品详情", "购买", "下单", "价格", "商城", "电商",
        "加购", "购物车", "规格", "product",
    ],
    "event_signup": [
        "活动", "报名", "活动报名", "报名表", "表单", "嘉宾", "日程",
        "峰会", "大会", "沙龙", "讲座", "赛事", "马拉松", "event", "signup",
    ],
    "store_booking": [
        "门店", "预约", "门店预约", "预订", "到店", "时段", "档期", "服务预约",
        "美容", "美发", "美容店", "宠物", "spa", "理发", "booking", "reservation",
    ],
}


def _select_high_quality_folder(user_prompt: str) -> str:
    """按关键词命中数挑出最相关的高质量样例目录；无命中默认 product_detail。"""
    prompt_lower = user_prompt.lower()
    best, best_hits = "product_detail", -1
    for folder, keywords in HIGH_QUALITY_KEYWORDS.items():
        hits = sum(1 for kw in keywords if kw.lower() in prompt_lower)
        if hits > best_hits:
            best, best_hits = folder, hits
    return best


def load_high_quality_example(folder_name: str) -> dict:
    """读取 golden_examples/high_quality/<folder> 下的三件套。"""
    target_dir = HIGH_QUALITY_DIR / folder_name
    result = {}
    for ext in ("wxml", "wxss", "js"):
        path = target_dir / f"index.{ext}"
        result[ext] = path.read_text(encoding="utf-8").strip() if path.exists() else ""
    return result


def get_golden_example(user_prompt: str) -> dict:
    """
    兜底输出（模型彻底失败时直接交付给用户的代码）。
    现已切换为 3 个「高质量黄金样例」，避免旧样例的 AI 味。
    旧 19 个样例仍保留在 gemma_core/golden_examples，可通过
    _legacy_get_golden_example_19() 调用，作为高质量样例缺失时的二级兜底。
    Returns: {'wxml': '...', 'wxss': '...', 'js': '...'}
    """
    folder = _select_high_quality_folder(user_prompt)
    files = load_high_quality_example(folder)
    if all(files.values()):
        return files
    # 高质量样例文件缺失时，回退到旧 19 样例容器
    return _legacy_get_golden_example_19(user_prompt)


def _legacy_get_golden_example_19(user_prompt: str) -> dict:
    """
    [已停用为默认兜底，保留为容器/二级备用]
    旧版兜底：在 19 个场景样例里按关键词匹配。
    Returns: {'wxml': '...', 'wxss': '...', 'js': '...'}
    """
    prompt_lower = user_prompt.lower()

    best_match = "product_detail" # default fallback
    max_hits = 0

    for scenario, keywords in SCENARIO_KEYWORDS.items():
        hits = sum(1 for kw in keywords if kw in prompt_lower)
        if hits > max_hits:
            max_hits = hits
            best_match = scenario

    return load_golden_from_folder(best_match)

def load_golden_from_folder(folder_name: str) -> dict:
    return load_golden_from_path(GOLDEN_DIR / folder_name)


def load_golden_from_path(target_dir: pathlib.Path) -> dict:
    
    result = {}
    for ext in ['wxml', 'wxss', 'js']:
        file_path = target_dir / f"index.{ext}"
        if file_path.exists():
            with open(file_path, "r", encoding="utf-8") as f:
                result[ext] = f.read().strip()
        else:
            # fallback to txt just in case
            txt_path = target_dir / f"{ext}.txt"
            if txt_path.exists():
                with open(txt_path, "r", encoding="utf-8") as f:
                    result[ext] = f.read().strip()
            else:
                result[ext] = ""
            
    return result

def format_golden_as_three_blocks(folder_name: str) -> str:
    """Formats a golden example for few-shot prompting."""
    data = load_golden_from_folder(folder_name)
    blocks = [
        "===WXML===",
        data.get("wxml", ""),
        "===WXSS===",
        data.get("wxss", ""),
        "===JS===",
        data.get("js", "")
    ]
    return "\n".join(blocks)
